# Generated by Django 3.2.5 on 2021-07-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210715_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='devliveredAt',
            new_name='deliveredAt',
        ),
    ]
